name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.runs-on }}
    strategy:
      fail-fast: false
      matrix:
        runs-on: [ubuntu-latest, windows-latest, macos-latest]
        configuration: [debug, release]
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Install dependencies
        if: matrix.runs-on == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y libsdl2-dev libopenal-dev libcurl-ocaml{,dev} libcurl3-{gnutls,nss} libcurl4 libcurl4-{gnutls,nss,openssl}-dev libcurlpp-dev
      - name: Build
        run: |
          ./waf configure -T ${{ matrix.configuration }}
          ./waf build
